/// Flutter icons Mypage
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Mypage
///      fonts:
///       - asset: fonts/Mypage.ttf
///
///
///
import 'package:flutter/widgets.dart';

class FooterIcons {
  FooterIcons._();

  static const _kFontFam = 'FooterIcons';
  static const String? _kFontPkg = null;

  static const IconData mycoupon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mypage = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData distribute = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
